# Generated by Django 4.1.3 on 2022-11-05 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_product_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='testingList',
            field=models.ManyToManyField(blank=True, related_name='testingList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='productWatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
