# Generated by Django 4.1.3 on 2022-11-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_product_testinglist_alter_product_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='testingList',
        ),
    ]
