# Generated by Django 4.1.3 on 2022-11-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_comment_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minStartBid',
            field=models.FloatField(default=0),
        ),
    ]
